version: '3'

services:
  api:
    build: backend/
    ports:
      - "${API_PORT:-3001}:3000"

  web:
    build: frontend/
    environment: 
      SERVER_API_HOST: ${SERVER_API_HOST:-http://api:3000/api}
      CLIENT_API_HOST: ${CLIENT_API_HOST:-http://127.0.0.1:3001/api}
    ports:
      - "${APP_PORT:-3000}:3000"
